### ISSUE TITLE
enters infinite loop on mutual depends in Remotes

### ISSUE THREAD

**Issue by cboettig** [r-pkgs/remotes#31]
Looks like this issue was fixed in the dev version of dplyr, but still impacts this package.  e.g. `remotes::install_github("hadley/dplyr")` fails due to recursive dependency between `dplyr` and `dtplyr`, 
https://github.com/hadley/dplyr/issues/1904.

Thanks!

**Comment by gaborcsardi** [comment]
Indeed, thanks!

**Comment by gaborcsardi** [comment]
I don't think this is fixed in `devtools`, actually. The "fix" was that they removed the actual circular dependency. (Which **is** the correct fix.)

Still, it would be nice to detect the circular dependencies, but I don't think that this is very important.

**Comment by jimhester** [comment]
This is handled in devtools, as part of https://github.com/hadley/devtools/pull/1067, in particular https://github.com/hadley/devtools/pull/1067/commits/a3dcdf8331014a8372a6ee4575ed1e2b1b1f35da

**Comment by gaborcsardi** [comment]
Yes, this is actually an issue, currently. Only if a package in `Remotes` is a soft dependency somewhere in the chain, though, because hard dependencies cannot be circular.

**Comment by gaborcsardi** [comment]
Thanks! I finally understood that this can be a problem, and fixed it, the same way as in `devtools`.
