### ISSUE TITLE
ENH: Export github_remote and other remote functions?

### ISSUE THREAD

**Issue by muschellij2** [r-pkgs/remotes#56]
Would it be possible to export `github_remote`?  This is the one I'm interested in, but other `remotes` classes may be relevant.   I wanted to use this useful function for a package, but have to use nonexport `:::`, resulting in warning/note.  

I know that it may be unstable (hence the non-export), but I think it may be useful to others to use.

**Comment by muschellij2** [comment]
I realize that I can manufacture similar functionality that I need with `parse_github_repo_spec`, so I don't know if this is necessary.

**Comment by gaborcsardi** [comment]
I would prefer not to export it, the package internals will likely to be rewritten soon. Let me know if this is a blocker for you.
