### ISSUE TITLE
install-github.me

### ISSUE THREAD

**Issue by Dasonk** [r-pkgs/remotes#61]
In the README it says you can install via install-github.me but the code provided is:

    source("https://install-github/r-pkgs/remotes")

which when I run it on my machine gives an address could not be resolved error.  Changing to 

    source("https://install-github.me/r-pkgs/remotes")

as implied by the previous line in the readme seems to fix the error. Can you confirm that this is what it should be and modify the README?

**Comment by gaborcsardi** [comment]
Thanks! Do you want to submit a PR?

**Comment by Dasonk** [comment]
Seems like this can be closed.
