### ISSUE TITLE
package_deps function overwrites provided arg 'repos'

### ISSUE THREAD

**Issue by dandelo** [r-pkgs/remotes#64]
The package_deps function accepts a 'repos' argument, but immediately overwrites it with the hard coded value "http://cran.rstudio.com".

**Comment by krlmlr** [comment]
Just saw this, too.

**Comment by gaborcsardi** [comment]
I don't think that this is true:

```r
❯ package_deps("igraph", repos = c(foobar = "https://non-existent-repo"))
Not on CRAN ----------------------------
 package installed available
 igraph  1.0.1     NA

❯ package_deps("igraph")
Needs update -----------------------------
 package      installed available
 iterators    NA        1.0.8
```

But maybe I am missing something.

**Comment by gaborcsardi** [comment]
Only the unspecified CRAN repo is overwritten here:
```r
  repos[repos == "@CRAN@"] <- "http://cran.rstudio.com"
```

**Comment by krlmlr** [comment]
Yes, that's what made me scratch my head.

**Comment by gaborcsardi** [comment]
So everything is OK, right?

**Comment by jimhester** [comment]
Yeah everything is fine, if you have an explicit repo set it is not overwritten.

Only the default `repos = @CRAN@`, which prompts the user to pick a CRAN repo. 👍  on Kirill's PR making this more clear.
